# =============================================
# Build config
# =============================================

root:             hipstersmoothie
dest:             <%= site.root %>
assets:           <%= site.dest %>/assets

# Data
data:             data/*.{json,yml}

# Templates
templates:        templates
includes:         <%= site.templates %>/includes/*.hbs
layouts:          <%= site.templates %>/layouts
content:          content
layout:           default.hbs

# Extensions
helpers:
  - <%= site.templates %>/helpers/*.js
  - handlebars-helper-br

plugins:
  - assemble-contrib-anchors
  - assemble-contrib-wordcount
  - assemble-contrib-toc

# Theme
theme:            theme
components:       <%= site.theme %>/components


# =============================================
# Project metadata
# =============================================

# Assemble metadata.
assemble:
  latest:         0.1  # change to <%= pkg.version %>

# GitHub
username:         hipstersmoothie
name:             hipstersmoothie # change to <%= pkg.name %>
download:
  source:         <%= pkg.homepage %>/archive/master.zip


# =============================================
# Site metadata
# =============================================

brand:            Andrew Lisowski
title:            HipsterSmoothie
lead:             I'm Andrew Lisowski, a 21-year-old software developer from San Diego.

version:          <%= pkg.version %>
description:      <%= pkg.description %>
license:
  type:           <%= pkg.licenses[0].type %>
  url:            <%= pkg.licenses[0].url %>


# Links
url:
  repo:           <%= pkg.homepage %>
  bugs:           <%= pkg.bugs.url %>?state=open
  ghpages:        https://<%= site.username %>.github.io/<%= pkg.name %>/

  # Site
  domain:         http://hipstersmoothie.com/
  blog:           <%= site.url.domain %>/blog/


# SEO/SEM
ga:
  id:             false
  domain:         assemble.github.io
  siteid:         false
  # Google Tags (see: https://www.google.com/tagmanager/)
  tags:           false

# Comments
disqus:
  enabled:        true
  shortname:      <%= pkg.name %>

# Social
social:
  twitter:
    via:          assemblejs
    username:     assemblejs
    related:      jonschlinkert:Assemble core team.
  facebook:       false
  linkedin:       false
  gplus:          false
  hn:             false
  google:         false

# Sharing
sharing:
  twitter:        false
  facebook:       false
  gplus:          false
  hn:             false
  google:         false
